# {@see https://github.com/gustarus/aws-cloud-formation-stacks}
# elastic-beanstalk-environment-health-monitor.yml

Parameters:
  Environment:
    Type: String
    Description: "Elastic beanstalk environment name."
  Namespace:
    Type: String
    Default: "some-namespace"
    Description: "Stack namespace to prefix child resources."
  Title:
    Type: String
    Description: "Resource title to prefix child resources."
  ReportingLevelThreshold:
    Type: String
    Default: "degraded"
    Description: "Environment health reporting level"
    AllowedValues: [ "warning", "degraded", "severe" ]
  TargetNotificationsTopics:
    Type: List<String>
    Description: "Simple notifications service topics arns."

Mappings:
  ReportingLevelMap:
    warning:
      value: 15
    degraded:
      value: 20
    severe:
      value: 25

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General'
        Parameters:
          - Environment
          - Namespace
          - Title
      - Label:
          default: 'Thresholds'
        Parameters:
          - ReportingLevelThreshold
      - Label:
          default: 'Actions'
        Parameters:
          - TargetNotificationsTopics

Resources:
  EnvironemntHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Title} - Environment - Health is not ok"
      AlarmDescription: "Alarm if on of the environment instances switched to desired level."
      AlarmActions: !Ref "TargetNotificationsTopics"
      OKActions: !Ref "TargetNotificationsTopics"
      Namespace: "AWS/ElasticBeanstalk"
      MetricName: "EnvironmentHealth"
      Dimensions:
        - Name: "EnvironmentName"
          Value: !Sub "${Environment}"
      Statistic: "Maximum"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      Threshold: !FindInMap [ "ReportingLevelMap", !Ref "ReportingLevelThreshold", "value"]
      EvaluationPeriods: 3
      Period: 60
      TreatMissingData: "missing"
